fetch("https://www.youtube.com/youtubei/v1/subscription/unsubscribe?prettyPrint=false", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.9,ru-RU;q=0.8,ru;q=0.7,pl-PL;q=0.6,pl;q=0.5",
    "authorization": "SAPISIDHASH 1717355644_e8e7a96428543f439c1c7945adc8a8093ac09cb1",
    "content-type": "application/json",
    "priority": "u=1, i",
    "sec-ch-ua": "\"Google Chrome\";v=\"125\", \"Chromium\";v=\"125\", \"Not.A/Brand\";v=\"24\"",
    "sec-ch-ua-arch": "\"x86\"",
    "sec-ch-ua-bitness": "\"64\"",
    "sec-ch-ua-full-version": "\"125.0.6422.113\"",
    "sec-ch-ua-full-version-list": "\"Google Chrome\";v=\"125.0.6422.113\", \"Chromium\";v=\"125.0.6422.113\", \"Not.A/Brand\";v=\"24.0.0.0\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-model": "\"\"",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-ch-ua-platform-version": "\"15.0.0\"",
    "sec-ch-ua-wow64": "?0",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "same-origin",
    "sec-fetch-site": "same-origin",
    "x-client-data": "CI62yQEIpLbJAQipncoBCNSKywEIlKHLAQjlmM0BCIWgzQEI4fXNAQji+s0BCNv8zQEI9IjOAQimic4BCOGTzgEI6ZPOAQjClc4BCNWYzgEY1+vNAQ==",
    "x-goog-authuser": "0",
    "x-goog-visitor-id": "CgtndGlnZ2JVOXhUYyjyiPOyBjIhCgJQTBIbEhcSFRMLFBUWFwwYGRobHB0eHw4PIBAREiA8",
    "x-origin": "https://www.youtube.com",
    "x-youtube-bootstrap-logged-in": "true",
    "x-youtube-client-name": "1",
    "x-youtube-client-version": "2.20240530.02.00"
  },
  "referrer": "https://www.youtube.com/@LukeMadeIt/videos",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"context\":{\"client\":{\"hl\":\"en\",\"gl\":\"PL\",\"remoteHost\":\"2a02:a317:4c3c:d400:4da5:eef7:1364:737\",\"deviceMake\":\"\",\"deviceModel\":\"\",\"visitorData\":\"CgtndGlnZ2JVOXhUYyjyiPOyBjIhCgJQTBIbEhcSFRMLFBUWFwwYGRobHB0eHw4PIBAREiA8\",\"userAgent\":\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36,gzip(gfe)\",\"clientName\":\"WEB\",\"clientVersion\":\"2.20240530.02.00\",\"osName\":\"Windows\",\"osVersion\":\"10.0\",\"originalUrl\":\"https://www.youtube.com/@LukeMadeIt/videos\",\"screenPixelDensity\":1,\"platform\":\"DESKTOP\",\"clientFormFactor\":\"UNKNOWN_FORM_FACTOR\",\"configInfo\":{\"appInstallData\":\"CPKI87IGELfvrwUQgvuwBRDM364FEIvPsAUQgOWwBRDvzbAFEI_EsAUQ1KGvBRDrk64FEPrwsAUQopKwBRDX5bAFEMf9tyIQ0I2wBRCL8rAFEJ7QsAUQlpWwBRDK-bAFEIPfrwUQ8-uwBRCmmrAFEOvbsAUQ463_EhD567AFEND4sAUQlp__EhCr77AFEPOhsAUQzfiwBRD-8LAFEOz2sAUQg7-wBRC34K4FEJeDsAUQ3ej-EhC36v4SEPSrsAUQ1t2wBRD40rAFEKLosAUQyfevBRDW57AFELDusAUQzPKwBRDuoq8FEJb7sAUQ1-mvBRDI-LAFEMiu_xIQltywBRCO2rAFEO6zsAUQ_PCwBRC--a8FEOrDrwUQ49GwBRDPqLAFEJT8rwUQu9iwBRC69LAFEPCcsAUQxtywBRCt47AFEKXC_hIQ1YiwBRCn47AFEL6KsAUQiOOvBRC2sf8SEKPtsAUQrNiwBRCs6rAFEPur_xIQvbauBRCa8K8FEN6I_xIQ5PSwBRC9mbAFEKDosAUQqJqwBRCC9rAFEM3XsAUQ2N2wBRD2q7AFEMnXsAUQt6uwBRCQjP8SEIrssAUQ0-GvBRCq2LAFEOvo_hIQ_IWwBRCNzLAFENuvrwUQgqL_EhCT77AFEPvasAUQ1_WwBRDi1K4FEInorgUQsdywBRCIh7AFENH4sAUQooGwBRDZya8FEOHssAUQ97H_EhCQsrAFEI_GsAUQ5fewBRDwsf8SKiBDQU1TRWhVSm9MMndETkhrQnFDUTlBdkwxQVFkQnc9PQ%3D%3D\"},\"screenDensityFloat\":1.100000023841858,\"userInterfaceTheme\":\"USER_INTERFACE_THEME_DARK\",\"timeZone\":\"Europe/Warsaw\",\"browserName\":\"Chrome\",\"browserVersion\":\"125.0.0.0\",\"acceptHeader\":\"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7\",\"deviceExperimentId\":\"ChxOek0zTlRrNE5qSTROVFV6T0RZeU1ERTRPUT09EPKI87IGGPKI87IG\",\"screenWidthPoints\":1745,\"screenHeightPoints\":828,\"utcOffsetMinutes\":120,\"connectionType\":\"CONN_CELLULAR_4G\",\"memoryTotalKbytes\":\"8000000\",\"mainAppWebInfo\":{\"graftUrl\":\"https://www.youtube.com/@LukeMadeIt/videos\",\"pwaInstallabilityStatus\":\"PWA_INSTALLABILITY_STATUS_CAN_BE_INSTALLED\",\"webDisplayMode\":\"WEB_DISPLAY_MODE_BROWSER\",\"isWebNativeShareAvailable\":true}},\"user\":{\"lockedSafetyMode\":false},\"request\":{\"useSsl\":true,\"consistencyTokenJars\":[{\"encryptedTokenJarContents\":\"AKreu9sHz0TQG2C5yRYZXEVASpj4yBSAm5ef6OSnKt_9tlb7jRWUZBhdoD_v4gb9Cav6uij-pyuzLeCnYSHr72FwcDJEoLhJDVGKthd8iV0dllwVeyCcJxqn9vc-lP2RxaiOYM0xkefC_i2bek7OznA-LFM_BqEUOTJq3_iijM7JXGN-kl9ClXXax1ZvWCn9DJyrkzz1lheZYtUKip3ju7L5_p9z6ZmL6fS_I13oyAQth6XVAy72N4PGs79b2LwBd8HFSM2SI_eFHqEXrJazC_Hu3Nh1eec_HBN9oRcZgqFoHD1L2Q\"}],\"internalExperimentFlags\":[]},\"clientScreenNonce\":\"AfB_CUPk2g_IsbhD\",\"clickTracking\":{\"clickTrackingParams\":\"CCQQ8FsiEwjNi6Ok0L2GAxW1WXoFHXY_EBQyCWNoYW5uZWxzNA==\"},\"adSignalsInfo\":{\"params\":[{\"key\":\"dt\",\"value\":\"1717355639039\"},{\"key\":\"flash\",\"value\":\"0\"},{\"key\":\"frm\",\"value\":\"0\"},{\"key\":\"u_tz\",\"value\":\"120\"},{\"key\":\"u_his\",\"value\":\"2\"},{\"key\":\"u_h\",\"value\":\"1080\"},{\"key\":\"u_w\",\"value\":\"1920\"},{\"key\":\"u_ah\",\"value\":\"1032\"},{\"key\":\"u_aw\",\"value\":\"1920\"},{\"key\":\"u_cd\",\"value\":\"30\"},{\"key\":\"bc\",\"value\":\"31\"},{\"key\":\"bih\",\"value\":\"828\"},{\"key\":\"biw\",\"value\":\"1730\"},{\"key\":\"brdim\",\"value\":\"0,0,0,0,1920,0,1920,1032,1745,828\"},{\"key\":\"vis\",\"value\":\"1\"},{\"key\":\"wgl\",\"value\":\"true\"},{\"key\":\"ca_type\",\"value\":\"image\"}],\"bid\":\"ANyPxKo00XgjYKflYVKtHqwFRhCbyXOI9C1DcusdTfr-TxLgjs0QlqCDGmd1MaPBjjx7sTevNnpK\"}},\"channelIds\":[\"UCG4pyCrLYfDsSaRUrBH1MKA\"],\"params\":\"CgIIAhgA\"}",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});